"use server"

import { readFile } from "fs/promises"
import { join } from "path"
import { existsSync } from "fs"

export type GuideType = "procedure" | "assessment-tool" | "checklist" | "form" | "record"

export interface Guide {
  id: string
  title: string
  description: string
  type: GuideType
  category: string
  parentStandard?: string
  owner: string
  status: "Draft" | "In Review" | "Ready to Use"
  version: string
  effectiveDate?: string
  filename: string
  topics: string[]
  difficulty: "Beginner" | "Intermediate" | "Advanced"
  readTime: string
  featured: boolean
}

// Guide metadata - extracted from the actual markdown files
const GUIDES: Guide[] = [
  // ============================================
  // PRODUCTION PROCEDURES (14 FINAL Documents)
  // ============================================
  {
    id: "proc-ai-rm-001",
    title: "AI Risk Management Procedure",
    description: "Comprehensive risk management procedure covering identification, assessment, mitigation, and monitoring of AI-related risks per Article 9 requirements. Includes GPAI risk assessment and third-party AI risk management.",
    type: "procedure",
    category: "Risk Management",
    parentStandard: "STD-AI-002",
    owner: "AI Act Program Manager",
    status: "Ready to Use",
    version: "2.0",
    effectiveDate: "2025-08-01",
    filename: "PROC-AI-RM-001_Example_Risk_Management_Procedure.md",
    topics: ["Risk identification", "Risk assessment", "Mitigation strategies", "Residual risk", "GPAI risk", "Third-party AI risk"],
    difficulty: "Advanced",
    readTime: "45 min",
    featured: true,
  },
  {
    id: "proc-ai-cls-001",
    title: "AI System Classification Procedure",
    description: "Step-by-step process for classifying AI systems according to EU AI Act risk categories including prohibited practices (Article 5), high-risk (Annex III), GPAI classification (Articles 51-56), and limited/minimal risk systems.",
    type: "procedure",
    category: "Classification",
    parentStandard: "STD-AI-001",
    owner: "AI Act Program Manager",
    status: "Ready to Use",
    version: "2.0",
    effectiveDate: "2025-08-01",
    filename: "PROC-AI-CLS-001_FINAL.md",
    topics: ["Risk classification", "Article 5 prohibited", "Annex III assessment", "GPAI classification", "Systemic risk"],
    difficulty: "Intermediate",
    readTime: "30 min",
    featured: true,
  },
  {
    id: "proc-ai-data-001",
    title: "Data Governance Procedure",
    description: "Comprehensive data governance procedure for AI training, validation, and testing datasets per Article 10 requirements. Covers data quality, bias detection, lineage documentation, and statistical appropriateness.",
    type: "procedure",
    category: "Data Management",
    parentStandard: "STD-AI-003",
    owner: "Data Management Lead",
    status: "Ready to Use",
    version: "2.0",
    effectiveDate: "2025-08-01",
    filename: "PROC-AI-DATA-001_FINAL.md",
    topics: ["Data quality", "Bias detection", "Data lineage", "Article 10 compliance", "Statistical appropriateness"],
    difficulty: "Advanced",
    readTime: "50 min",
    featured: true,
  },
  {
    id: "proc-ai-doc-001",
    title: "Technical Documentation Procedure",
    description: "Procedure for creating and maintaining Annex IV compliant technical documentation for high-risk AI systems. Includes GPAI documentation requirements (Annex XI/XII).",
    type: "procedure",
    category: "Documentation",
    parentStandard: "STD-AI-004",
    owner: "Technical Documentation Manager",
    status: "Ready to Use",
    version: "2.0",
    effectiveDate: "2025-08-01",
    filename: "PROC-AI-DOC-001_FINAL.md",
    topics: ["Annex IV documentation", "Technical specifications", "GPAI documentation", "Version control", "Audit readiness"],
    difficulty: "Intermediate",
    readTime: "45 min",
    featured: false,
  },
  {
    id: "proc-ai-log-001",
    title: "Logging & Traceability Procedure",
    description: "Procedure for implementing Article 12 compliant automatic logging capabilities with 10-year retention requirements for high-risk AI systems.",
    type: "procedure",
    category: "Operations",
    parentStandard: "STD-AI-005",
    owner: "IT Operations Manager",
    status: "Ready to Use",
    version: "2.0",
    effectiveDate: "2025-08-01",
    filename: "PROC-AI-LOG-001_FINAL.md",
    topics: ["Automatic logging", "10-year retention", "Article 12 compliance", "Audit trails", "Log integrity"],
    difficulty: "Intermediate",
    readTime: "35 min",
    featured: false,
  },
  {
    id: "proc-ai-trans-001",
    title: "Transparency & User Information Procedure",
    description: "Procedure for ensuring Article 13 and Article 50 transparency obligations including instructions for use, AI interaction disclosure, and synthetic content labeling.",
    type: "procedure",
    category: "Transparency",
    parentStandard: "STD-AI-006",
    owner: "Compliance Officer",
    status: "Ready to Use",
    version: "2.0",
    effectiveDate: "2025-08-01",
    filename: "PROC-AI-TRANS-001_FINAL.md",
    topics: ["Instructions for use", "AI disclosure", "Synthetic content labeling", "Article 50 obligations", "Deployer information"],
    difficulty: "Intermediate",
    readTime: "40 min",
    featured: false,
  },
  {
    id: "proc-ai-ho-001",
    title: "Human Oversight Procedure",
    description: "Comprehensive procedure for implementing Article 14 human oversight requirements including oversight mechanisms, competency requirements, and intervention protocols.",
    type: "procedure",
    category: "Governance",
    parentStandard: "STD-AI-007",
    owner: "AI Governance Lead",
    status: "Ready to Use",
    version: "2.0",
    effectiveDate: "2025-08-01",
    filename: "PROC-AI-HO-001_FINAL.md",
    topics: ["Human oversight", "Article 14 compliance", "Intervention protocols", "Competency requirements", "Override capabilities"],
    difficulty: "Advanced",
    readTime: "55 min",
    featured: true,
  },
  {
    id: "proc-ai-ars-001",
    title: "Accuracy, Robustness & Cybersecurity Procedure",
    description: "Procedure for ensuring Article 15 compliance covering accuracy metrics, robustness testing, and cybersecurity measures for high-risk AI systems.",
    type: "procedure",
    category: "Technical",
    parentStandard: "STD-AI-008",
    owner: "AI Engineering Lead",
    status: "Ready to Use",
    version: "2.0",
    effectiveDate: "2025-08-01",
    filename: "PROC-AI-ARS-001_FINAL.md",
    topics: ["Accuracy metrics", "Robustness testing", "Cybersecurity", "Article 15 compliance", "Adversarial testing"],
    difficulty: "Advanced",
    readTime: "45 min",
    featured: false,
  },
  {
    id: "proc-ai-qms-001",
    title: "Quality Management System Procedure",
    description: "Procedure for establishing and maintaining an Article 17 compliant Quality Management System for AI providers covering all QMS elements.",
    type: "procedure",
    category: "Quality",
    parentStandard: "STD-AI-009",
    owner: "Quality Manager",
    status: "Ready to Use",
    version: "2.0",
    effectiveDate: "2025-08-01",
    filename: "PROC-AI-QMS-001_FINAL.md",
    topics: ["QMS establishment", "Article 17 compliance", "Quality policy", "Resource management", "Design controls"],
    difficulty: "Advanced",
    readTime: "50 min",
    featured: false,
  },
  {
    id: "proc-ai-ca-001",
    title: "Conformity Assessment Procedure",
    description: "Procedure for conducting conformity assessments per Articles 43, 47, and 48 including self-assessment, notified body involvement, and CE marking requirements.",
    type: "procedure",
    category: "Certification",
    parentStandard: "STD-AI-010",
    owner: "Compliance Officer",
    status: "Ready to Use",
    version: "2.0",
    effectiveDate: "2025-08-01",
    filename: "PROC-AI-CA-001_FINAL.md",
    topics: ["Conformity assessment", "CE marking", "Annex V declaration", "Notified body", "Self-assessment"],
    difficulty: "Advanced",
    readTime: "60 min",
    featured: false,
  },
  {
    id: "proc-ai-reg-001",
    title: "EU Database Registration Procedure",
    description: "Procedure for registering high-risk AI systems and GPAI models in the EU database per Articles 49 and 71 with Annex VIII data requirements.",
    type: "procedure",
    category: "Registration",
    parentStandard: "STD-AI-011",
    owner: "Regulatory Affairs Manager",
    status: "Ready to Use",
    version: "2.0",
    effectiveDate: "2025-08-01",
    filename: "PROC-AI-REG-001_FINAL.md",
    topics: ["EU database registration", "Article 49", "Article 71", "Annex VIII data", "GPAI registration"],
    difficulty: "Intermediate",
    readTime: "35 min",
    featured: false,
  },
  {
    id: "proc-ai-pmm-001",
    title: "Post-Market Monitoring Procedure",
    description: "Comprehensive procedure for Article 72 post-market monitoring including PMMP establishment, data collection, analysis, and proportionate response to identified issues.",
    type: "procedure",
    category: "Operations",
    parentStandard: "STD-AI-012",
    owner: "Post-Market Surveillance Manager",
    status: "Ready to Use",
    version: "2.0",
    effectiveDate: "2025-08-01",
    filename: "PROC-AI-PMM-001_FINAL.md",
    topics: ["Post-market monitoring", "Article 72 compliance", "PMMP", "Data collection", "Corrective actions"],
    difficulty: "Advanced",
    readTime: "55 min",
    featured: false,
  },
  {
    id: "proc-ai-inc-001",
    title: "Incident Management Procedure",
    description: "Procedure for managing and reporting serious incidents per Article 73 including detection, investigation, notification to authorities, and corrective actions.",
    type: "procedure",
    category: "Operations",
    parentStandard: "STD-AI-013",
    owner: "Incident Response Manager",
    status: "Ready to Use",
    version: "2.0",
    effectiveDate: "2025-08-01",
    filename: "PROC-AI-INC-001_FINAL.md",
    topics: ["Serious incidents", "Article 73 reporting", "72-hour notification", "Root cause analysis", "Corrective actions"],
    difficulty: "Intermediate",
    readTime: "40 min",
    featured: false,
  },
  {
    id: "proc-ai-lit-001",
    title: "AI Literacy & Training Procedure",
    description: "Procedure for ensuring Article 4 AI literacy compliance including competency frameworks, training programs, and ongoing education for all personnel involved with AI systems.",
    type: "procedure",
    category: "Training",
    parentStandard: "STD-AI-014",
    owner: "Learning & Development Manager",
    status: "Ready to Use",
    version: "2.0",
    effectiveDate: "2025-08-01",
    filename: "PROC-AI-LIT-001_FINAL.md",
    topics: ["AI literacy", "Article 4 compliance", "Competency matrix", "Training programs", "Certification tracking"],
    difficulty: "Beginner",
    readTime: "35 min",
    featured: false,
  },
  // ============================================
  // NEW PROCEDURES (Created Dec 2025)
  // ============================================
  {
    id: "proc-ai-dev-001",
    title: "AI Development Lifecycle Procedure",
    description: "Comprehensive procedure for AI system development covering requirements, design, implementation, testing, and deployment phases with gate reviews.",
    type: "procedure",
    category: "Development",
    parentStandard: "STD-AI-009",
    owner: "AI Engineering Lead",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "PROC-AI-DEV-001_FINAL.md",
    topics: ["Development lifecycle", "Gate reviews", "Design controls", "V&V", "Release management"],
    difficulty: "Advanced",
    readTime: "45 min",
    featured: true,
  },
  {
    id: "proc-ai-vendor-001",
    title: "AI Vendor Management Procedure",
    description: "Procedure for managing AI vendors and third-party AI components including due diligence, risk assessment, and ongoing monitoring.",
    type: "procedure",
    category: "Vendor Management",
    parentStandard: "STD-AI-009",
    owner: "Procurement Manager",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "PROC-AI-VENDOR-001_FINAL.md",
    topics: ["Vendor assessment", "Due diligence", "Contract management", "Third-party risk", "Supplier monitoring"],
    difficulty: "Intermediate",
    readTime: "40 min",
    featured: false,
  },
  {
    id: "proc-ai-gov-001",
    title: "AI Governance Procedure",
    description: "Procedure for establishing AI governance structures including governance bodies, approval processes, and decision-making frameworks.",
    type: "procedure",
    category: "Governance",
    parentStandard: "STD-AI-009",
    owner: "AI Governance Lead",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "PROC-AI-GOV-001_FINAL.md",
    topics: ["Governance bodies", "AI Committee", "Approval processes", "Decision framework", "Accountability"],
    difficulty: "Advanced",
    readTime: "35 min",
    featured: true,
  },
  {
    id: "proc-ai-chg-001",
    title: "AI Change Management Procedure",
    description: "Procedure for managing changes to AI systems including substantial modification assessment, change approval, and implementation.",
    type: "procedure",
    category: "Change Management",
    parentStandard: "STD-AI-009",
    owner: "Change Manager",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "PROC-AI-CHG-001_FINAL.md",
    topics: ["Change control", "Substantial modification", "CAB", "Emergency changes", "Impact assessment"],
    difficulty: "Intermediate",
    readTime: "35 min",
    featured: false,
  },
  {
    id: "proc-ai-capa-001",
    title: "Corrective and Preventive Action Procedure",
    description: "Procedure for managing CAPA including root cause analysis, corrective actions, preventive measures, and effectiveness verification.",
    type: "procedure",
    category: "Quality",
    parentStandard: "STD-AI-009",
    owner: "Quality Manager",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "PROC-AI-CAPA-001_FINAL.md",
    topics: ["CAPA", "Root cause analysis", "5 Whys", "Fishbone", "Effectiveness verification"],
    difficulty: "Intermediate",
    readTime: "30 min",
    featured: false,
  },
  {
    id: "proc-ai-deploy-001",
    title: "AI Deployment Procedure",
    description: "Procedure for deploying AI systems to production including pre-deployment checks, deployment execution, and post-deployment verification.",
    type: "procedure",
    category: "Operations",
    parentStandard: "STD-AI-009",
    owner: "Deployment Manager",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "PROC-AI-DEPLOY-001_FINAL.md",
    topics: ["Deployment", "Rollback", "Pre-deployment checks", "Go-live", "Production readiness"],
    difficulty: "Intermediate",
    readTime: "35 min",
    featured: false,
  },
  {
    id: "proc-ai-test-001",
    title: "AI Testing Procedure",
    description: "Comprehensive testing procedure covering functional, performance, bias, security, and compliance testing for AI systems.",
    type: "procedure",
    category: "Quality",
    parentStandard: "STD-AI-008",
    owner: "QA Manager",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "PROC-AI-TEST-001_FINAL.md",
    topics: ["Testing", "Bias testing", "Security testing", "Model validation", "UAT"],
    difficulty: "Advanced",
    readTime: "45 min",
    featured: false,
  },
  {
    id: "proc-ai-conf-001",
    title: "Configuration Management Procedure",
    description: "Procedure for managing AI system configurations including model parameters, hyperparameters, and version control.",
    type: "procedure",
    category: "Operations",
    parentStandard: "STD-AI-005",
    owner: "Configuration Manager",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "PROC-AI-CONF-001_FINAL.md",
    topics: ["Configuration management", "Version control", "Model lineage", "Baseline management"],
    difficulty: "Intermediate",
    readTime: "25 min",
    featured: false,
  },
  {
    id: "proc-ai-trn-001",
    title: "AI Training and Competency Procedure",
    description: "Procedure for ensuring AI literacy and competency per Article 4 and Article 14 requirements.",
    type: "procedure",
    category: "Training",
    parentStandard: "STD-AI-014",
    owner: "Training Manager",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "PROC-AI-TRN-001_FINAL.md",
    topics: ["AI literacy", "Competency", "Training records", "Refresher training"],
    difficulty: "Beginner",
    readTime: "25 min",
    featured: false,
  },
  // ============================================
  // CHECKLISTS
  // ============================================
  {
    id: "chk-ai-rm-001",
    title: "Risk Assessment Checklist",
    description: "Comprehensive checklist for AI risk assessments covering health, safety, fundamental rights, and technical risks.",
    type: "checklist",
    category: "Risk Management",
    parentStandard: "STD-AI-002",
    owner: "AI Risk Manager",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "CHK-AI-RM-001_FINAL.md",
    topics: ["Risk assessment", "Health risks", "Safety risks", "Fundamental rights"],
    difficulty: "Intermediate",
    readTime: "20 min",
    featured: false,
  },
  {
    id: "chk-ai-ca-001",
    title: "Conformity Assessment Checklist",
    description: "Complete EU AI Act conformity assessment checklist covering Articles 9-17, 47, 48, 71, 72.",
    type: "checklist",
    category: "Certification",
    parentStandard: "STD-AI-010",
    owner: "Compliance Officer",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "CHK-AI-CA-001_FINAL.md",
    topics: ["Conformity assessment", "CE marking", "EU AI Act compliance"],
    difficulty: "Advanced",
    readTime: "30 min",
    featured: true,
  },
  {
    id: "chk-ai-doc-001",
    title: "Technical Documentation Checklist",
    description: "Annex IV technical documentation checklist covering all required documentation elements.",
    type: "checklist",
    category: "Documentation",
    parentStandard: "STD-AI-004",
    owner: "Documentation Manager",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "CHK-AI-DOC-001_FINAL.md",
    topics: ["Annex IV", "Technical documentation", "Documentation completeness"],
    difficulty: "Intermediate",
    readTime: "25 min",
    featured: false,
  },
  {
    id: "chk-ai-doc-002",
    title: "Documentation Completeness Checklist",
    description: "Comprehensive checklist to verify all AI system documentation is complete and current.",
    type: "checklist",
    category: "Documentation",
    parentStandard: "STD-AI-004",
    owner: "Documentation Manager",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "CHK-AI-DOC-002_FINAL.md",
    topics: ["Documentation review", "Completeness", "Currency"],
    difficulty: "Beginner",
    readTime: "20 min",
    featured: false,
  },
  {
    id: "chk-ai-rm-002",
    title: "Risk Control Effectiveness Checklist",
    description: "Checklist for verifying the effectiveness of implemented risk controls.",
    type: "checklist",
    category: "Risk Management",
    parentStandard: "STD-AI-002",
    owner: "AI Risk Manager",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "CHK-AI-RM-002_FINAL.md",
    topics: ["Control effectiveness", "Risk controls", "Verification"],
    difficulty: "Intermediate",
    readTime: "15 min",
    featured: false,
  },
  {
    id: "chk-ai-pmm-001",
    title: "Post-Market Monitoring Checklist",
    description: "Checklist for post-market monitoring activities per Article 72 requirements.",
    type: "checklist",
    category: "Operations",
    parentStandard: "STD-AI-012",
    owner: "Post-Market Surveillance Manager",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "CHK-AI-PMM-001_FINAL.md",
    topics: ["Post-market monitoring", "Article 72", "Surveillance"],
    difficulty: "Intermediate",
    readTime: "15 min",
    featured: false,
  },
  {
    id: "chk-ai-trans-001",
    title: "Transparency Requirements Checklist",
    description: "Checklist for Article 13 and Article 50 transparency requirements.",
    type: "checklist",
    category: "Transparency",
    parentStandard: "STD-AI-006",
    owner: "Compliance Officer",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "CHK-AI-TRANS-001_FINAL.md",
    topics: ["Transparency", "Article 13", "Article 50", "User disclosure"],
    difficulty: "Intermediate",
    readTime: "20 min",
    featured: false,
  },
  {
    id: "chk-ai-reg-001",
    title: "Registration Requirements Checklist",
    description: "Checklist for EU database registration requirements per Article 71.",
    type: "checklist",
    category: "Registration",
    parentStandard: "STD-AI-011",
    owner: "Regulatory Affairs Manager",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "CHK-AI-REG-001_FINAL.md",
    topics: ["EU database", "Registration", "Article 71"],
    difficulty: "Intermediate",
    readTime: "15 min",
    featured: false,
  },
  // ============================================
  // FORMS
  // ============================================
  {
    id: "form-ai-cls-001",
    title: "AI Classification Form",
    description: "Form for documenting AI system risk classification decisions.",
    type: "form",
    category: "Classification",
    parentStandard: "STD-AI-001",
    owner: "AI Act Program Manager",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "FORM-AI-CLS-001_FINAL.md",
    topics: ["Classification", "Risk level", "Prohibited practices", "Annex III"],
    difficulty: "Beginner",
    readTime: "15 min",
    featured: false,
  },
  {
    id: "form-ai-cls-002",
    title: "Classification Review Request Form",
    description: "Form for requesting review or change of AI system classification.",
    type: "form",
    category: "Classification",
    parentStandard: "STD-AI-001",
    owner: "AI Act Program Manager",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "FORM-AI-CLS-002_FINAL.md",
    topics: ["Classification review", "Reclassification", "Change request"],
    difficulty: "Beginner",
    readTime: "10 min",
    featured: false,
  },
  {
    id: "form-ai-rm-001",
    title: "Risk Assessment Form",
    description: "Form for documenting AI system risk assessments.",
    type: "form",
    category: "Risk Management",
    parentStandard: "STD-AI-002",
    owner: "AI Risk Manager",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "FORM-AI-RM-001_FINAL.md",
    topics: ["Risk assessment", "Risk identification", "Risk analysis"],
    difficulty: "Intermediate",
    readTime: "20 min",
    featured: false,
  },
  {
    id: "form-ai-rm-003",
    title: "Risk Treatment Form",
    description: "Form for documenting risk treatment decisions and control implementation.",
    type: "form",
    category: "Risk Management",
    parentStandard: "STD-AI-002",
    owner: "AI Risk Manager",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "FORM-AI-RM-003_FINAL.md",
    topics: ["Risk treatment", "Control implementation", "Residual risk"],
    difficulty: "Intermediate",
    readTime: "15 min",
    featured: false,
  },
  {
    id: "form-ai-inc-001",
    title: "Incident Report Form",
    description: "Form for reporting AI system incidents per Article 73 requirements.",
    type: "form",
    category: "Operations",
    parentStandard: "STD-AI-013",
    owner: "Incident Response Manager",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "FORM-AI-INC-001_FINAL.md",
    topics: ["Incident reporting", "Article 73", "Serious incidents"],
    difficulty: "Intermediate",
    readTime: "15 min",
    featured: false,
  },
  {
    id: "form-ai-reg-001",
    title: "EU Database Registration Form",
    description: "Form for EU database registration per Article 71.",
    type: "form",
    category: "Registration",
    parentStandard: "STD-AI-011",
    owner: "Regulatory Affairs Manager",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "FORM-AI-REG-001_FINAL.md",
    topics: ["EU database", "Registration", "Article 71"],
    difficulty: "Intermediate",
    readTime: "15 min",
    featured: false,
  },
  {
    id: "form-ai-reg-002",
    title: "Registration Update Form",
    description: "Form for updating existing EU database registrations.",
    type: "form",
    category: "Registration",
    parentStandard: "STD-AI-011",
    owner: "Regulatory Affairs Manager",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "FORM-AI-REG-002_FINAL.md",
    topics: ["Registration update", "EU database", "Status change"],
    difficulty: "Beginner",
    readTime: "10 min",
    featured: false,
  },
  {
    id: "form-ai-trans-001",
    title: "Transparency Disclosure Form",
    description: "Form for documenting transparency disclosures for AI systems.",
    type: "form",
    category: "Transparency",
    parentStandard: "STD-AI-006",
    owner: "Compliance Officer",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "FORM-AI-TRANS-001_FINAL.md",
    topics: ["Transparency", "AI disclosure", "Synthetic content"],
    difficulty: "Beginner",
    readTime: "15 min",
    featured: false,
  },
  {
    id: "form-ai-exception-001",
    title: "Exception Request Form",
    description: "Form for requesting exceptions to AI compliance requirements.",
    type: "form",
    category: "Governance",
    parentStandard: "STD-AI-009",
    owner: "Compliance Officer",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "FORM-AI-EXCEPTION-001_FINAL.md",
    topics: ["Exception", "Deviation", "Compensating controls"],
    difficulty: "Intermediate",
    readTime: "15 min",
    featured: false,
  },
  // Assessment Tools
  {
    id: "tool-controls-catalog",
    title: "AI Act Controls Catalog",
    description: "Complete catalog of controls mapped to EU AI Act requirements, with implementation guidance and evidence requirements.",
    type: "assessment-tool",
    category: "Compliance",
    owner: "AI Act Program Manager",
    status: "Ready to Use",
    version: "1.0",
    filename: "AI-ACT-CONTROLS-CATALOG.md",
    topics: ["Controls", "Implementation", "Evidence", "Article mapping"],
    difficulty: "Intermediate",
    readTime: "35 min",
    featured: true,
  },
  {
    id: "tool-role-determination",
    title: "AI Act Role Determination Process",
    description: "Guide for determining which AI Act roles (Provider, Deployer, Distributor, Importer) apply to your organization for each AI system.",
    type: "assessment-tool",
    category: "Compliance",
    owner: "Enterprise Control Governance",
    status: "Ready to Use",
    version: "1.0",
    filename: "AI-ACT-ROLE-DETERMINATION-PROCESS.md",
    topics: ["Provider", "Deployer", "Distributor", "Importer", "Role obligations"],
    difficulty: "Beginner",
    readTime: "15 min",
    featured: true,
  },
  {
    id: "tool-risk-classification",
    title: "AI System Risk Classification Template",
    description: "Template and decision tree for classifying AI systems according to EU AI Act risk levels with step-by-step guidance.",
    type: "assessment-tool",
    category: "Classification",
    owner: "AI Act Program Manager",
    status: "Ready to Use",
    version: "1.0",
    filename: "AI-SYSTEM-RISK-CLASSIFICATION-TEMPLATE.md",
    topics: ["Risk levels", "Decision tree", "Classification criteria", "Documentation"],
    difficulty: "Beginner",
    readTime: "20 min",
    featured: false,
  },
  {
    id: "tool-workbook-guide",
    title: "Consolidated Workbook Guide",
    description: "User guide for the AI Act Consolidated Workbook, explaining how to use the compliance tracking spreadsheet effectively.",
    type: "assessment-tool",
    category: "Compliance",
    owner: "AI Act Program Manager",
    status: "Ready to Use",
    version: "1.0",
    filename: "CONSOLIDATED-WORKBOOK-GUIDE.md",
    topics: ["Workbook usage", "Compliance tracking", "Progress monitoring", "Reporting"],
    difficulty: "Beginner",
    readTime: "15 min",
    featured: false,
  },
  // ============================================
  // RECORDS
  // ============================================
  {
    id: "rec-ai-audit-001",
    title: "AI Audit Record",
    description: "Document internal and external audits of AI systems with findings and corrective actions.",
    type: "record",
    category: "Quality Management",
    parentStandard: "STD-AI-009",
    owner: "Quality Manager",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "REC-AI-AUDIT-001_FINAL.md",
    topics: ["Audit", "Findings", "Corrective actions", "QMS"],
    difficulty: "Intermediate",
    readTime: "15 min",
    featured: false,
  },
  {
    id: "rec-ai-ca-001",
    title: "Conformity Assessment Record",
    description: "Document conformity assessment activities and outcomes for high-risk AI systems.",
    type: "record",
    category: "Certification",
    parentStandard: "STD-AI-010",
    owner: "Compliance Officer",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "REC-AI-CA-001_FINAL.md",
    topics: ["Conformity assessment", "CE marking", "Certification"],
    difficulty: "Advanced",
    readTime: "20 min",
    featured: false,
  },
  {
    id: "rec-ai-capa-001",
    title: "CAPA Record",
    description: "Document corrective and preventive actions for AI system non-conformities.",
    type: "record",
    category: "Quality Management",
    parentStandard: "STD-AI-009",
    owner: "Quality Manager",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "REC-AI-CAPA-001_FINAL.md",
    topics: ["CAPA", "Root cause", "Corrective action", "Preventive action"],
    difficulty: "Intermediate",
    readTime: "15 min",
    featured: false,
  },
  {
    id: "rec-ai-chg-001",
    title: "Change Control Record",
    description: "Document changes to AI systems including impact assessment and approvals.",
    type: "record",
    category: "Configuration",
    parentStandard: "STD-AI-009",
    owner: "Change Manager",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "REC-AI-CHG-001_FINAL.md",
    topics: ["Change control", "Impact assessment", "Approval", "Substantial modification"],
    difficulty: "Intermediate",
    readTime: "15 min",
    featured: false,
  },
  {
    id: "rec-ai-cls-001",
    title: "Classification Record",
    description: "Document AI system risk classification decisions and supporting rationale.",
    type: "record",
    category: "Classification",
    parentStandard: "STD-AI-001",
    owner: "AI Act Program Manager",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "REC-AI-CLS-001_FINAL.md",
    topics: ["Classification", "Risk level", "Decision rationale"],
    difficulty: "Beginner",
    readTime: "10 min",
    featured: false,
  },
  {
    id: "rec-ai-data-001",
    title: "Data Governance Record",
    description: "Document data governance activities for AI training and validation datasets.",
    type: "record",
    category: "Data Management",
    parentStandard: "STD-AI-003",
    owner: "Data Governance Manager",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "REC-AI-DATA-001_FINAL.md",
    topics: ["Data governance", "Dataset", "Data quality", "Bias assessment"],
    difficulty: "Intermediate",
    readTime: "15 min",
    featured: false,
  },
  {
    id: "rec-ai-data-002",
    title: "Data Quality Assessment Record",
    description: "Document data quality assessments and remediation activities.",
    type: "record",
    category: "Data Management",
    parentStandard: "STD-AI-003",
    owner: "Data Governance Manager",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "REC-AI-DATA-002_FINAL.md",
    topics: ["Data quality", "Assessment", "Remediation"],
    difficulty: "Intermediate",
    readTime: "15 min",
    featured: false,
  },
  {
    id: "rec-ai-deploy-001",
    title: "Deployment Record",
    description: "Document AI system deployment activities and go-live approvals.",
    type: "record",
    category: "Operations",
    parentStandard: "STD-AI-009",
    owner: "Deployment Manager",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "REC-AI-DEPLOY-001_FINAL.md",
    topics: ["Deployment", "Go-live", "Production readiness"],
    difficulty: "Intermediate",
    readTime: "15 min",
    featured: false,
  },
  {
    id: "rec-ai-doc-001",
    title: "Technical Documentation Record",
    description: "Document technical documentation status and Annex IV compliance.",
    type: "record",
    category: "Documentation",
    parentStandard: "STD-AI-004",
    owner: "Documentation Manager",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "REC-AI-DOC-001_FINAL.md",
    topics: ["Technical documentation", "Annex IV", "Documentation status"],
    difficulty: "Intermediate",
    readTime: "15 min",
    featured: false,
  },
  {
    id: "rec-ai-gov-001",
    title: "Governance Decision Record",
    description: "Document AI governance committee decisions and approvals.",
    type: "record",
    category: "Governance",
    parentStandard: "STD-AI-009",
    owner: "AI Governance Committee",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "REC-AI-GOV-001_FINAL.md",
    topics: ["Governance", "Decision", "Approval", "Committee"],
    difficulty: "Intermediate",
    readTime: "10 min",
    featured: false,
  },
  {
    id: "rec-ai-ho-001",
    title: "Human Oversight Record",
    description: "Document human oversight activities and intervention events.",
    type: "record",
    category: "Human Oversight",
    parentStandard: "STD-AI-007",
    owner: "Human Oversight Manager",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "REC-AI-HO-001_FINAL.md",
    topics: ["Human oversight", "Intervention", "Override", "Article 14"],
    difficulty: "Intermediate",
    readTime: "15 min",
    featured: false,
  },
  {
    id: "rec-ai-inc-001",
    title: "Incident Record",
    description: "Document AI system incidents and serious incident reports per Article 73.",
    type: "record",
    category: "Operations",
    parentStandard: "STD-AI-013",
    owner: "Incident Response Manager",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "REC-AI-INC-001_FINAL.md",
    topics: ["Incident", "Serious incident", "Article 73", "Reporting"],
    difficulty: "Intermediate",
    readTime: "15 min",
    featured: true,
  },
  {
    id: "rec-ai-log-001",
    title: "Logging Record",
    description: "Document automatic logging configuration and log retention activities.",
    type: "record",
    category: "Operations",
    parentStandard: "STD-AI-005",
    owner: "System Administrator",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "REC-AI-LOG-001_FINAL.md",
    topics: ["Logging", "Retention", "Article 12", "Audit trail"],
    difficulty: "Intermediate",
    readTime: "10 min",
    featured: false,
  },
  {
    id: "rec-ai-pmm-001",
    title: "Post-Market Monitoring Record",
    description: "Document post-market monitoring activities and findings per Article 72.",
    type: "record",
    category: "Operations",
    parentStandard: "STD-AI-012",
    owner: "Post-Market Surveillance Manager",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "REC-AI-PMM-001_FINAL.md",
    topics: ["Post-market monitoring", "Article 72", "Surveillance", "Findings"],
    difficulty: "Intermediate",
    readTime: "15 min",
    featured: false,
  },
  {
    id: "rec-ai-reg-001",
    title: "Registration Record",
    description: "Document EU database registration activities per Article 71.",
    type: "record",
    category: "Registration",
    parentStandard: "STD-AI-011",
    owner: "Regulatory Affairs Manager",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "REC-AI-REG-001_FINAL.md",
    topics: ["Registration", "EU database", "Article 71"],
    difficulty: "Intermediate",
    readTime: "10 min",
    featured: false,
  },
  {
    id: "rec-ai-rm-001",
    title: "Risk Assessment Record",
    description: "Document AI system risk assessments and risk register entries.",
    type: "record",
    category: "Risk Management",
    parentStandard: "STD-AI-002",
    owner: "AI Risk Manager",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "REC-AI-RM-001_FINAL.md",
    topics: ["Risk assessment", "Risk register", "Risk identification"],
    difficulty: "Intermediate",
    readTime: "15 min",
    featured: true,
  },
  {
    id: "rec-ai-rm-002",
    title: "Risk Treatment Record",
    description: "Document risk treatment decisions and control implementation.",
    type: "record",
    category: "Risk Management",
    parentStandard: "STD-AI-002",
    owner: "AI Risk Manager",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "REC-AI-RM-002_FINAL.md",
    topics: ["Risk treatment", "Control implementation", "Residual risk"],
    difficulty: "Intermediate",
    readTime: "15 min",
    featured: false,
  },
  {
    id: "rec-ai-rm-003",
    title: "Risk Review Record",
    description: "Document periodic risk reviews and risk status updates.",
    type: "record",
    category: "Risk Management",
    parentStandard: "STD-AI-002",
    owner: "AI Risk Manager",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "REC-AI-RM-003_FINAL.md",
    topics: ["Risk review", "Risk status", "Periodic review"],
    difficulty: "Intermediate",
    readTime: "10 min",
    featured: false,
  },
  {
    id: "rec-ai-test-001",
    title: "Testing Record",
    description: "Document AI system testing activities and test results.",
    type: "record",
    category: "Testing",
    parentStandard: "STD-AI-008",
    owner: "Test Manager",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "REC-AI-TEST-001_FINAL.md",
    topics: ["Testing", "Test results", "Validation", "Verification"],
    difficulty: "Intermediate",
    readTime: "15 min",
    featured: false,
  },
  {
    id: "rec-ai-trans-001",
    title: "Transparency Record",
    description: "Document transparency disclosures and user notifications.",
    type: "record",
    category: "Transparency",
    parentStandard: "STD-AI-006",
    owner: "Compliance Officer",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "REC-AI-TRANS-001_FINAL.md",
    topics: ["Transparency", "Disclosure", "User notification", "Article 50"],
    difficulty: "Beginner",
    readTime: "10 min",
    featured: false,
  },
  {
    id: "rec-ai-trn-001",
    title: "Training Record",
    description: "Document AI literacy training completion and competency assessments.",
    type: "record",
    category: "Training",
    parentStandard: "STD-AI-014",
    owner: "Training Manager",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "REC-AI-TRN-001_FINAL.md",
    topics: ["Training", "AI literacy", "Competency", "Article 4"],
    difficulty: "Beginner",
    readTime: "10 min",
    featured: false,
  },
  {
    id: "rec-ai-vendor-001",
    title: "Vendor Assessment Record",
    description: "Document AI vendor due diligence and assessment activities.",
    type: "record",
    category: "Vendor Management",
    parentStandard: "STD-AI-009",
    owner: "Vendor Manager",
    status: "Ready to Use",
    version: "1.0",
    effectiveDate: "2025-12-11",
    filename: "REC-AI-VENDOR-001_FINAL.md",
    topics: ["Vendor assessment", "Due diligence", "Third-party risk"],
    difficulty: "Intermediate",
    readTime: "15 min",
    featured: false,
  },
]

const GUIDES_BASE_PATH = join(process.cwd(), "src/lib/data/guides")

/**
 * Get all guides
 */
export async function getGuides(type?: GuideType): Promise<Guide[]> {
  if (type) {
    return GUIDES.filter(g => g.type === type)
  }
  return GUIDES
}

/**
 * Get a guide by ID
 */
export async function getGuideById(id: string): Promise<Guide | null> {
  return GUIDES.find(g => g.id === id) || null
}

/**
 * Get guide content (markdown)
 */
export async function getGuideContent(id: string): Promise<string | null> {
  const guide = GUIDES.find(g => g.id === id)
  if (!guide) return null

  // Map guide type to subdirectory
  const subdirMap: Record<GuideType, string> = {
    "procedure": "procedures",
    "assessment-tool": "assessment-tools",
    "checklist": "checklists",
    "form": "forms",
    "record": "records",
  }
  const subdir = subdirMap[guide.type] || "procedures"
  const filePath = join(GUIDES_BASE_PATH, subdir, guide.filename)

  if (!existsSync(filePath)) {
    console.error(`Guide file not found: ${filePath}`)
    return null
  }

  try {
    return await readFile(filePath, "utf-8")
  } catch (error) {
    console.error(`Error reading guide file: ${filePath}`, error)
    return null
  }
}

/**
 * Get guide statistics
 */
export async function getGuideStats() {
  const procedures = GUIDES.filter(g => g.type === "procedure")
  const assessmentTools = GUIDES.filter(g => g.type === "assessment-tool")
  const checklists = GUIDES.filter(g => g.type === "checklist")
  const forms = GUIDES.filter(g => g.type === "form")
  const records = GUIDES.filter(g => g.type === "record")
  const featured = GUIDES.filter(g => g.featured)

  const byCategory: Record<string, number> = {}
  for (const guide of GUIDES) {
    byCategory[guide.category] = (byCategory[guide.category] || 0) + 1
  }

  return {
    total: GUIDES.length,
    procedures: procedures.length,
    assessmentTools: assessmentTools.length,
    checklists: checklists.length,
    forms: forms.length,
    records: records.length,
    featured: featured.length,
    byCategory,
    byStatus: {
      draft: GUIDES.filter(g => g.status === "Draft").length,
      inReview: GUIDES.filter(g => g.status === "In Review").length,
      ready: GUIDES.filter(g => g.status === "Ready to Use").length,
    },
  }
}

/**
 * Get featured guides
 */
export async function getFeaturedGuides(): Promise<Guide[]> {
  return GUIDES.filter(g => g.featured)
}

/**
 * Get guides by category
 */
export async function getGuidesByCategory(category: string): Promise<Guide[]> {
  return GUIDES.filter(g => g.category === category)
}

/**
 * Get unique categories
 */
export async function getGuideCategories(): Promise<string[]> {
  const categories = new Set(GUIDES.map(g => g.category))
  return Array.from(categories).sort()
}
